### ISSUE TITLE
Border colours and fonts are applied inconsistently

### ISSUE THREAD

**Issue by TabithaLarkin** [simonhaenisch/md-to-pdf#29] opened 2019-03-06 17:50 UTC
So I've run into a bit of an issue I'm scratching my head over. Seems like it could be another race condition type thing.

Sometimes when I compile only some of the CSS rules are applied.

This is the expected output:
![css-applied](https://user-images.githubusercontent.com/3467306/53902014-313df100-4038-11e9-9995-b8437492ed27.png)

This is what sometimes happens:
![css-not-applied](https://user-images.githubusercontent.com/3467306/53902015-313df100-4038-11e9-99ba-66d91cb01909.png)

There doesn't seem to be a consistent way of making this happen, though it does happen quite often.

**Comment by simonhaenisch** [comment] 2019-03-06 18:50
Just to help debugging this, how are you adding the styles (stylesheet file, remote url, using the `css` option)? Thanks.

**Comment by StephenLarkin** [comment] 2019-03-07 10:46
I'm using two stylesheet files, the github one to provide some defaults and then a smaller custom one for some targeted changes.

My first thought was that the second file wasn't loading, but then I realised that the heading colour has been overridden to the dark blue colour, so the file does seem to be loading.

```json
{
    "stylesheet": [
        "node_modules/github-markdown-css/github-markdown.css",
        "style/md-style.css"
    ],
    "body_class": "markdown-body"
}
```

Thanks for helping again, I know I'm kinda bombarding you with issues we're finding, but your help is really appreciated.

**Comment by simonhaenisch** [comment] 2019-03-07 11:43
All good, please keep opening issues if you have problems/questions (:

This started out as a very simple CLI tool because I wanted to write my assignments in markdown and hand them in as PDFs... now the goal is to make it a thin layer to connect the underlying tools (marked, puppeteer) and make it easy to use, while still exposing the full options of the underlying tools.

I haven't used it within another Node project yet, but I'm interested to make it work well for that use-case, too.

So do I read correctly that this issue is solved?

**Comment by StephenLarkin** [comment] 2019-03-07 12:31
No, it's not I was just explaining that I had ruled out the second stylesheet not loading.

**Comment by simonhaenisch** [comment] 2019-03-07 14:37
So `md-style.css` sets the heading's color to blue, the font-weight to light and the bottom border to blue, but sometimes only the color is applied and not the other rules, even though they are from the same stylesheet?

**Comment by StephenLarkin** [comment] 2019-03-08 00:47
Yup, that is correct. It's like it's getting only part way through loading the CSS.

**Comment by simonhaenisch** [comment] 2019-03-08 09:49
Would you be able to share your `md-styles.css`, please? After a quick Google search it seems to me that the issue would rather be related to the stylesheet content (see e. g. https://stackoverflow.com/a/14872618/2897426), because stylesheets don't get applied piece by piece (that would cause many repaints) but only after the whole stylesheet has been parsed... if there is a parsing error somewhere, it'll apply up to where it was parseable.

**Comment by StephenLarkin** [comment] 2019-03-08 15:04
Here's a copy of it.

[md-style-upload.txt](https://github.com/simonhaenisch/md-to-pdf/files/2946274/md-style-upload.txt)

**Comment by simonhaenisch** [comment] 2019-03-08 15:19
Just wondering, the file seems like it's been compiled from a CSS preprocessor... could it be that the "race condition" is between your compiler and `md-to-pdf`? Or are you not compiling the css file every time you run your docs generation?

**Comment by StephenLarkin** [comment] 2019-03-08 15:36
That was my initial thought as well, and it was the first thing I ruled out.

**Comment by simonhaenisch** [comment] 2020-02-28 13:41
Closing this because I don't know how to reproduce this. If you run into this again after upgrading to version 3 (`npm install md-to-pdf@next`), please let me know and I'll reopen it.

**Closed by simonhaenisch** 2020-02-28 13:41 UTC
Labels: bug
