### ISSUE TITLE
bug: listen EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by yalinglee** [simonhaenisch/md-to-pdf#81] opened 2021-01-10 06:24 UTC
**Context:**

- version (`md-to-pdf -v`): 3.2.1
- platform (Unix, macOS, Windows): macOS
- node version: v12.18.0

**Describe the bug:**

I get the following error intermittently when generating several PDF files in a row using the API:
```
listen EADDRINUSE: address already in use :::xxxxx
```
Is there a way to catch this error and retry again right after it happens? Thanks in advance for the help!

**Comment by simonhaenisch** [comment] 2021-01-12 14:18
Sorry for the late reply. I assume you're running multiple `mdToPdf` commands concurrently?

A quick-fix work-around would probably be to set a different port for each command, for example:

```js
import { mdToPdf } from 'md-to-pdf';

const files = ['docs/foo.md', 'docs/bar.md'];

async function main() {
  await Promise.all(files.map((path, i) => mdToPdf({ path }, { port: 3000 + i });
});

main()
  .then(() => process.exit())
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```

---

I'll see whether I can find some time to implement a new way of specifying multiple input files (i. e. `{ paths: [...] }`), so that the same file server is used for all files, instead of launching one for every file. That'll also be a bit faster (less overhead per conversion).

**Comment by simonhaenisch** [comment] 2021-01-12 14:38
Hm I've just checked `get-port` and it does actually have some logic to prevent the same port from being used across the same process to prevent race conditions (see https://github.com/sindresorhus/get-port#beware).

Would you mind sharing how exactly you are invoking `md-to-pdf`? Are you launching different child processes? BTW just in case you're not aware yet, via the CLI it's already possible to specify multiple input files, e. g. via shell globbing.

**Comment by yalinglee** [comment] 2021-01-12 18:33
Thanks for getting back! I'm using `md-to-pdf` in a nodejs application. I have an array of maps that I loop through. Here's a simplified example:
```
import {mdToPdf} from 'md-to-pdf';

async function createPdfs() {
  const pdfs = [{
    'content': 'some text',
    'path': 'some path'
  }];

  for (const pdf of pdfs) {
    await mdToPdf({content: pdf.content}, {dest: pdf.path});
  }
}
```
I don't think this operation is concurrent, so not sure why I would run into this error.

**Comment by simonhaenisch** [comment] 2021-01-12 19:07
Yeah that's not concurrent, so I'm really not sure why you would run into this error then 🤷🏻‍♂️ Do you get a stack trace that you could share next time you run into this error?

**Comment by simonhaenisch** [comment] 2021-01-13 09:41
Also, could you try to use

```js
let i = 3000;

for (const pdf of pdfs) {
  await mdToPdf({content: pdf.content}, {dest: pdf.path, port: i++});
}
```

and see whether that prevents this error from happening? If not, then there must be some other service interfering with one of the ports.

**Comment by yalinglee** [comment] 2021-01-13 18:44
Thank you for the suggestion! I'll report back if I see this error again.

**Comment by simonhaenisch** [comment] 2021-05-14 11:43
Closing this for now as I couldn't reproduce it and there's been no additional info.

**Closed by simonhaenisch** 2021-05-14 11:43 UTC
Labels: question
