### ISSUE TITLE
question: how to use as lamdba function on AWS

### ISSUE THREAD

**Issue by Mohammedismaeell** [simonhaenisch/md-to-pdf#73] opened 2020-05-17 16:55 UTC
**Context:**

- version (`md-to-pdf -3.1.0`):
- platform (AWS):
- node version:12

**Describe the bug:**
Hi, thanks for all job done here :)
I try to use this code in my lambda function and everything seems to be fine the problem is my lambda size gets very big 153MB when I remove the import lambda size gets to 1.3MB

Thank you in advance    
Mohammed

**Comment by simonhaenisch** [comment] 2020-05-17 17:10
This is not a bug. If you don't know enough about puppeteer and headless browsers and how to run them in a serverless environment like AWS lambdas, then sorry I can't help you at the moment because of lack of spare time.

However, if you figure it out, please let me know cause I've been wanting to try this for a while now 😄

You can have a look at https://github.com/alixaxel/chrome-aws-lambda and you can make a fork of md-to-pdf and try to get it working. Afaik the Chromium binary download size goes down to 30-something MB with chrome-aws-lambda because of some compression. During execution the lambda will still need the same amount of memory though.

**Comment by simonhaenisch** [comment] 2022-01-28 19:54
Closing this for now but if anyone makes progress on this, feel free to drop a comment with a solution to share with others (:

**Closed** 2022-01-28 19:53 UTC
Labels: question
