### ISSUE TITLE
bug: No such file or directory, open 'C:\workspace\angular-demo\pdf\**\*.md'

### ISSUE THREAD

**Issue by cheikhnadiouf** [simonhaenisch/md-to-pdf#287] opened 2024-01-02 09:52 UTC
This command `md-to-pdf ./pdf/**/*.md` can't find the multiple path folders
I am using version 5.2.4

`generating PDF from ./pdf/**/*.md
    → ENOENT: no such file or directory, open 'C:\workspace\angular-demo\pdf\**\*.md'
ListrError: Something went wrong
    at C:\workspace\angular-demo\node_modules\listr\index.js:102:18
    at async main (C:\workspace\angular-demo\node_modules\md-to-pdf\dist\cli.js:120:5) {
  errors: [
    [Error: ENOENT: no such file or directory, open 'C:\workspace\angular-demo\pdf\**\*.md'] {
      errno: -4058,
      code: 'ENOENT',
      syscall: 'open',
      path: 'C:\\workspace\\angular-demo\\pdf\\**\\*.md'
    }
  ],
  context: [Object: null prototype] {}
}
`

**Comment by simonhaenisch** [comment] 2024-01-02 12:02
Duplicate of #136 I guess. Wildcard expansion is not supported by cmd.exe... use powershell or WSL (windows subsystem for linux), or figure out how cmd.exe can expand a list of files into the command 😅

**Closed by simonhaenisch** 2024-01-02 12:02 UTC
Labels: question

**Comment by cheikhnadiouf** [comment] 2024-01-02 13:03
Guys, guys, guys 
Closing a ticket without even waiting for a feedback of a user is the best way of discrediting all open source solutions.
Even on powershell , in windows it is not working. You should check it yourself.
