### ISSUE TITLE
feature: embedded mastodon posts

### ISSUE THREAD

**Issue by invisiblegaudi** [simonhaenisch/md-to-pdf#234] opened 2023-07-29 00:38 UTC
**Problem:**

Related to #122 

When outputting HTML, it is desirable to embed mastodon posts rather than have a link to them taking the reader away from the page.

**Solution:**

I would like to have a flag e.g. `--embed-socials` to add the necessary HTML and js around the links to embed any urls to mastodon posts

**Comment by invisiblegaudi** [comment] 2023-07-29 00:39
willing to do the work for this

**Comment by simonhaenisch** [comment] 2023-07-30 11:14
Closing as a duplicate of #233 because it's basically the same thing but just for a different social platform.

See https://github.com/simonhaenisch/md-to-pdf/issues/233#issuecomment-1657110930, imo best idea for it is to be solved with custom Marked extensions that can be published as npm packages, and we just need to make it easier to use those in `md-to-pdf`.

**Closed by simonhaenisch** 2023-07-30 11:14 UTC
Labels: feature
