### ISSUE TITLE
feature: include another md file

### ISSUE THREAD

**Issue by gigaga** [simonhaenisch/md-to-pdf#56] opened 2020-01-13 10:07 UTC
**Problem:**

Currently, to have a complete PDF documentation, the whole of chapter have to be written just in one md file.

**Solution:**

That will great if it is possible to inclide another md file like that for example :
``` [include](chapter1.md)```

**Comment by simonhaenisch** [comment] 2020-01-14 06:15
Closing as a duplicate of #34.

I'll post a solution there that uses a custom renderer for Marked.

**Closed by simonhaenisch** 2020-01-14 06:15 UTC
Labels: feature
