### ISSUE TITLE
bug: links with # anchor are not rendered correctly

### ISSUE THREAD

**Issue by aescripts** [simonhaenisch/md-to-pdf#96] opened 2021-07-28 15:40 UTC
**Context:**
# in web links are converted to %23

- version (`md-to-pdf -v`): 4.0.0
- platform (Unix, macOS, Windows): macOS
- node version: v14.16.1

**Describe the bug:**
For example this link:
https://website.com/faq/#floating-licenses
is rendered in the pdf as:
http://website.com/faq/%23floating-licenses

**Comment by simonhaenisch** [comment] 2021-07-31 12:14
Hey, I'm currently on holiday, so replies might take longer than usual.

I cannot reproduce this, just tried on macOS as well (with Node 16.5 though but I doubt that makes a difference). Copied above link into a markdown file, then ran `md-to-pdf` on it via the CLI; also tried the `--as-html` option. Both the HTML and PDF have the correct URI with the `#` unescaped. I even checked the PDF as raw text and it has a  
`/URI (https://website.com/faq/#floating-licenses)>>>>`  
object in it.

Are there any other markdown-related packages/plugins you are using that might cause this? Can you share your config?

**Comment by simonhaenisch** [comment] 2021-08-09 12:11
Closing this for now since there's nothing I can do about it. If someone has more info about this or how to reproduce it, please leave it here and I'll reopen.

**Closed by simonhaenisch** 2021-08-09 12:11 UTC
Labels: bug

**Comment by aescripts** [comment] 2021-08-09 14:38
> Are there any other markdown-related packages/plugins you are using that might cause this? 

Not that i am aware of but where would i check this?

>Can you share your config?

Sure, here it is: 

```json
{
  "stylesheet": [
    "https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/3.0.1/github-markdown.min.css"
  ],
  "css": ".page-break { page-break-after: always; } .markdown-body { font-size: 11px; } .markdown-body pre > code { white-space: pre-wrap; }",
  "body_class": "markdown-body",
  "highlight_style": "github",
  "stylesheet_encoding": "utf-8"
}
```

**Comment by simonhaenisch** [comment] 2021-08-10 07:33
Tried with the exact same config and still can't reproduce this. Added the following into a markdown file and none of the links end up with that `%23` encoding.

```markdown
https://website.com/faq/#floating-licenses

<https://website.com/faq/#floating-licenses>

[https://website.com/faq/#floating-licenses](https://website.com/faq/#floating-licenses)
```

Unless you can provide a full example, I can't help, sorry 😔
